edlingerma/MMP2b

app/assets/stylesheets/footer.scss
app/assets/stylesheets/hamburger.scss
app/assets/stylesheets/header.scss
app/assets/stylesheets/home.scss
app/views/challenges/_home.html.erb

Add media queries and links

---

app/assets/stylesheets/show.scss
app/models/activity.rb
app/models/challenge.rb
app/models/entry.rb
app/views/challenges/edit.html.erb

Add validations for descriptions

---

app/assets/stylesheets/footer.scss
app/controllers/challenges_controller.rb
app/controllers/entries_controller.rb
app/controllers/users_controller.rb
app/models/activity.rb
app/views/challenges/_challenge.json.jbuilder
app/views/challenges/_footer.html.erb
app/views/challenges/show.html.erb
app/views/users/_user.json.jbuilder
app/views/users/index.json.jbuilder
app/views/users/show.json.jbuilder

Add json API

---

app/assets/stylesheets/form.scss
app/assets/stylesheets/header.scss
app/assets/stylesheets/home.scss
app/assets/stylesheets/show.scss
app/views/challenges/_home.html.erb
app/views/challenges/show_owner.html.erb

Add tables and refactor styling

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/challenges_controller.rb
app/controllers/entries_controller.rb
app/models/activity.rb
app/models/challenge.rb
app/models/entry.rb
app/views/challenges/show_owner.html.erb
config/environments/production.rb

Solve some issues

---

app/assets/stylesheets/home.scss
app/views/challenges/_home.html.erb

Styling refactoring

---

app/assets/stylesheets/home.scss
app/models/entry.rb
app/views/challenges/_home.html.erb

Adjust width in ChallengeContainer

Adjust width in ChallengeContainer

---

Gemfile.lock
app/assets/stylesheets/header.scss
app/assets/stylesheets/home.scss
app/assets/stylesheets/show.scss
app/controllers/challenges_controller.rb
app/javascript/packs/stringReplace.js
app/views/challenges/_home.html.erb
app/views/challenges/my_challenges.html.erb

Add new display option for Requests

Add new display option for Requests

---

Gemfile
Gemfile.lock
app/assets/stylesheets/footer.scss
app/views/challenges/_home.html.erb
db/schema.rb
db/seeds.rb

Prepare seeds for usertesting

---

app/assets/stylesheets/hamburger.scss
app/assets/stylesheets/show.scss
app/views/challenges/_activity_fields.html.erb

Fix: wrong z-index at hamburger menu

Fix: wrong z-index at hamburger menu

---

README.md
app/assets/stylesheets/application.scss
app/assets/stylesheets/footer.scss
app/assets/stylesheets/form.scss
app/assets/stylesheets/hamburger.scss
app/assets/stylesheets/home.scss
app/assets/stylesheets/show.scss
app/models/challenge.rb
app/views/challenges/_form.html.erb
app/views/layouts/application.html.erb

Fix styling for mobile devices

Fix styling for mobile devices

---

config/storage.yml

Change key and make it secret via env

Change key and make it secret via env

---

app/controllers/application_controller.rb
app/controllers/challenges_controller.rb
app/controllers/entries_controller.rb
app/controllers/requests_controller.rb
app/controllers/users_controller.rb
app/models/entry.rb
app/views/challenges/show.html.erb

Refactor all controllers

---

app/controllers/challenges_controller.rb
app/controllers/requests_controller.rb
app/views/challenges/show_owner.html.erb
app/views/requests/remove_confirmation.html.erb
config/routes.rb

Add confirmation before removing user

Add confirmation before removing user

---

Gemfile
Gemfile.lock
app/assets/stylesheets/header.scss
app/assets/stylesheets/users.scss
app/models/user.rb
app/views/challenges/_footer.html.erb
app/views/challenges/_header.html.erb
config/initializers/rswag-ui.rb
config/initializers/rswag_api.rb
config/routes.rb
spec/requests/challenges_spec.rb
spec/swagger_helper.rb
swagger/v1/swagger.yaml

This will add Swagger, requests-Tests and some more validations

This will add Swagger, requests-Tests and some more validations

---

app/assets/stylesheets/global.scss
app/assets/stylesheets/hamburger.scss
app/assets/stylesheets/header.scss
app/models/user.rb
app/views/challenges/_activity_fields.html.erb
db/seeds.rb
spec/models/user_spec.rb

Fix bug with Facebook

---

app/views/layouts/application.html.erb

HOTFIX move script-tag to be valid - w3c

HOTFIX move script-tag to be valid - w3c

---

app/controllers/challenges_controller.rb

HOTFIX Request could not be created

HOTFIX Request could not be created

---

app/assets/stylesheets/home.scss
app/controllers/entries_controller.rb
app/models/activity.rb
app/models/entry.rb
app/views/entries/_form.html.erb
config/application.rb

Add several hotfixes

---

app/assets/stylesheets/form.scss
app/models/activity.rb
app/models/challenge.rb
app/views/users/_form.html.erb

Sign up Form break & Title validations

Refactoring changes
